name: animate_number
description: "Animate number is Flutter package to create easy slide animation number"
version: 0.2.2
homepage: https://farhan-fadila.web.app/
repository: https://github.com/farhanfadila1717/animate_number

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  after_layout: ^1.2.0
  flutter:
    sdk: flutter
  scroll_to_index: ^3.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
